"""Snakemake Pipeline Builder: generate production Snakefiles.

Converts pipeline steps into a Snakefile with proper wildcard handling,
DAG validation, and cluster config.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from biopipe.pipelines.nextflow_builder import PipelineStep, DEFAULT_STEPS


# ── Snakemake Templates ─────────────────────────────────────────────────────

SNAKEMAKE_RULES: dict[str, dict[str, Any]] = {
    "fastqc": {
        "input": "data/{sample}_{read}.fastq.gz",
        "output": "results/fastqc/{sample}_{read}_fastqc.html",
        "threads": 2,
        "shell": "fastqc -t {threads} -o results/fastqc/ {input}",
        "container": "docker://biocontainers/fastqc:0.12.1--hdfd78af_0",
    },
    "fastp": {
        "input": ["data/{sample}_R1.fastq.gz", "data/{sample}_R2.fastq.gz"],
        "output": [
            "results/trimmed/{sample}_R1.trimmed.fq.gz",
            "results/trimmed/{sample}_R2.trimmed.fq.gz",
            "results/trimmed/{sample}.fastp.json",
        ],
        "threads": 4,
        "shell": (
            "fastp -i {input[0]} -I {input[1]} "
            "-o {output[0]} -O {output[1]} "
            "--thread {threads} -j {output[2]}"
        ),
        "container": "docker://biocontainers/fastp:0.23.4--hadf994f_0",
    },
    "bwa_mem": {
        "input": {
            "r1": "results/trimmed/{sample}_R1.trimmed.fq.gz",
            "r2": "results/trimmed/{sample}_R2.trimmed.fq.gz",
            "ref": "config['genome']",
        },
        "output": "results/aligned/{sample}.sorted.bam",
        "threads": 8,
        "shell": (
            'bwa mem -t {threads} -R "@RG\\tID:{wildcards.sample}\\tSM:{wildcards.sample}\\tPL:ILLUMINA" '
            "{input.ref} {input.r1} {input.r2} | "
            "samtools sort -@ {threads} -o {output}"
        ),
        "container": "docker://biocontainers/bwa:0.7.18--he4a0461_0",
    },
    "samtools_index": {
        "input": "results/aligned/{sample}.sorted.bam",
        "output": "results/aligned/{sample}.sorted.bam.bai",
        "threads": 1,
        "shell": "samtools index {input}",
        "container": "docker://biocontainers/samtools:1.19--h50ea8bc_0",
    },
    "mark_duplicates": {
        "input": "results/aligned/{sample}.sorted.bam",
        "output": [
            "results/dedup/{sample}.dedup.bam",
            "results/dedup/{sample}.metrics.txt",
        ],
        "threads": 2,
        "shell": (
            "gatk MarkDuplicates -I {input} -O {output[0]} -M {output[1]}"
        ),
        "container": "docker://broadinstitute/gatk:4.5.0.0",
    },
    "haplotypecaller": {
        "input": {
            "bam": "results/dedup/{sample}.dedup.bam",
            "ref": "config['genome']",
        },
        "output": "results/vcf/{sample}.g.vcf.gz",
        "threads": 4,
        "shell": (
            "gatk HaplotypeCaller -R {input.ref} -I {input.bam} -O {output} -ERC GVCF"
        ),
        "container": "docker://broadinstitute/gatk:4.5.0.0",
    },
    "multiqc": {
        "input": "results/",
        "output": "results/multiqc/multiqc_report.html",
        "threads": 1,
        "shell": "multiqc results/ -o results/multiqc/",
        "container": "docker://biocontainers/multiqc:1.21--pyhdfd78af_0",
    },
}


class SnakemakeBuilder:
    """Generate Snakemake pipelines from step definitions."""

    def build(
        self,
        step_names: list[str],
        samples: list[str] | None = None,
        genome: str = "hg38",
        config_extra: dict[str, Any] | None = None,
    ) -> dict[str, str]:
        """Generate Snakefile and cluster config.

        Returns:
            Dict with keys "Snakefile" and "config.yaml".
        """
        if samples is None:
            samples = ["sample1"]

        snakefile = self._build_snakefile(step_names, samples, genome)
        config_yaml = self._build_config(samples, genome, config_extra)
        cluster_yaml = self._build_cluster_config(step_names)

        return {
            "Snakefile": snakefile,
            "config.yaml": config_yaml,
            "cluster.yaml": cluster_yaml,
        }

    def _build_snakefile(
        self, step_names: list[str], samples: list[str], genome: str,
    ) -> str:
        """Generate Snakefile content."""
        lines = [
            "# BioPipe-CLI Generated Snakefile",
            f"# Genome: {genome}",
            f"# Steps: {', '.join(step_names)}",
            "# Generated by BioPipe-CLI (https://github.com/biopipe/biopipe-cli)",
            "",
            'configfile: "config.yaml"',
            "",
            f"SAMPLES = config['samples']",
            "",
        ]

        # Determine final outputs for rule all
        final_outputs = self._get_final_outputs(step_names, samples)
        lines.append("rule all:")
        lines.append("    input:")
        for out in final_outputs:
            lines.append(f'        expand("{out}", sample=SAMPLES),')
        lines.append("")

        # Generate rules
        for name in step_names:
            if name in SNAKEMAKE_RULES:
                lines.extend(self._render_rule(name, SNAKEMAKE_RULES[name]))
            else:
                lines.extend(self._render_generic_rule(name))

        return "\n".join(lines)

    def _render_rule(self, name: str, template: dict) -> list[str]:
        """Render a single Snakemake rule."""
        lines = [f"rule {name}:"]

        # Input
        inp = template["input"]
        if isinstance(inp, dict):
            lines.append("    input:")
            for k, v in inp.items():
                lines.append(f'        {k} = "{v}",')
        elif isinstance(inp, list):
            lines.append("    input:")
            for v in inp:
                lines.append(f'        "{v}",')
        else:
            lines.append(f'    input: "{inp}"')

        # Output
        out = template["output"]
        if isinstance(out, list):
            lines.append("    output:")
            for v in out:
                lines.append(f'        "{v}",')
        else:
            lines.append(f'    output: "{out}"')

        # Threads
        lines.append(f"    threads: {template.get('threads', 1)}")

        # Container
        if template.get("container"):
            lines.append(f'    container: "{template["container"]}"')

        # Shell
        lines.append("    shell:")
        lines.append(f'        "{template["shell"]}"')
        lines.append("")

        return lines

    def _render_generic_rule(self, name: str) -> list[str]:
        """Render a generic rule for unknown steps."""
        return [
            f"rule {name}:",
            f'    input: "results/{{sample}}.input"',
            f'    output: "results/{name}/{{sample}}.output"',
            "    threads: 1",
            "    shell:",
            f'        "{name} {{input}} > {{output}}"',
            "",
        ]

    def _get_final_outputs(self, step_names: list[str], samples: list[str]) -> list[str]:
        """Determine the final output files for rule all."""
        outputs = []
        last = step_names[-1] if step_names else "output"

        if last in SNAKEMAKE_RULES:
            out = SNAKEMAKE_RULES[last]["output"]
            if isinstance(out, list):
                outputs.append(out[0])
            else:
                outputs.append(out)
        else:
            outputs.append(f"results/{last}/{{sample}}.output")

        return outputs

    def _build_config(
        self, samples: list[str], genome: str, extra: dict | None,
    ) -> str:
        """Generate config.yaml."""
        lines = [
            "# BioPipe-CLI Pipeline Configuration",
            "",
            f'genome: "$HOME/.biopipe/genomes/{genome}/{genome}.fa"',
            "",
            "samples:",
        ]
        for s in samples:
            lines.append(f"  - {s}")

        if extra:
            lines.append("")
            for k, v in extra.items():
                lines.append(f"{k}: {v}")

        return "\n".join(lines)

    def _build_cluster_config(self, step_names: list[str]) -> str:
        """Generate cluster.yaml for SLURM submission."""
        lines = [
            "# SLURM Cluster Config for Snakemake",
            "# Usage: snakemake --cluster-config cluster.yaml --cluster 'sbatch ...'",
            "",
            "__default__:",
            "    partition: compute",
            "    cpus: 1",
            "    mem: 4G",
            "    time: '01:00:00'",
            "    output: logs/{rule}_{wildcards}.out",
            "",
        ]

        for name in step_names:
            if name in SNAKEMAKE_RULES:
                tmpl = SNAKEMAKE_RULES[name]
                lines.append(f"{name}:")
                lines.append(f"    cpus: {tmpl.get('threads', 1)}")
                # Estimate memory from Nextflow defaults
                step = DEFAULT_STEPS.get(name)
                mem = f"{step.memory_gb}G" if step else "8G"
                time = f"{step.time_h:02d}:00:00" if step else "02:00:00"
                lines.append(f"    mem: {mem}")
                lines.append(f"    time: '{time}'")
                lines.append("")

        return "\n".join(lines)
