"""Critic Agent Module for Multi-Agent Debate.

The Critic Agent acts as a safety and logic reviewer. Before the Main Agent 
is allowed to save a pipeline script or finish execution, the Critic evaluates 
the script for logical errors, missing quality controls, and bioinformatics best practices.

If the Critic rejects the script, the feedback is injected back into the Main Agent's
context loop, forcing it to debate and fix the problem.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from .types import LLMProvider, Message, Role
from .hooks import Hook, HookPoint


@dataclass
class CriticResult:
    """The result of a Critic Agent's review."""
    approved: bool
    feedback: str


class CriticAgent:
    """Independent LLM Agent that reviews bioinformatics pipelines."""

    def __init__(self, llm: LLMProvider) -> None:
        self._llm = llm
        self._system_prompt = (
            "You are an expert Bioinformatics Critic Agent. Your job is to review "
            "shell/Nextflow/Snakemake scripts generated by another AI agent. "
            "Check for: missing FASTQC, missing multiqc, missing index logic, "
            "incorrect BAM sorting, resource mismanagement, and logical deadlocks. "
            "Reply strictly with JSON:\n"
            '{"approved": true, "feedback": "Looks good"}\n'
            "OR\n"
            '{"approved": false, "feedback": "You forgot to sort the BAM file before indexing."}'
        )

    async def review_script(self, script_content: str, user_prompt: str) -> CriticResult:
        """Analyze a drafted script against the original user prompt."""
        messages = [
            Message(role=Role.SYSTEM, content=self._system_prompt),
            Message(
                role=Role.USER, 
                content=f"User asked for: {user_prompt}\n\nDRAFT SCRIPT:\n```\n{script_content}\n```\nReview it."
            )
        ]

        response = await self._llm.generate(messages, tools=[])
        
        try:
            # Attempt to parse json from the response
            # Sometimes LLM puts markdown blocks around JSON
            clean_text = response.content.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_text)
            
            # Fail closed on malformed schema.
            if "approved" not in data or "feedback" not in data:
                return CriticResult(False, "Critic response missing required fields")
            
            return CriticResult(
                approved=bool(data["approved"]),
                feedback=str(data["feedback"])
            )
        except json.JSONDecodeError:
            # If the critic fails to emit valid JSON, reject and request regeneration.
            return CriticResult(False, "Critic failed JSON validation")


class CriticHook(Hook):
    """Hook that integrates Critic Agent into the runtime loop."""

    def __init__(self, critic: CriticAgent, original_prompt: str) -> None:
        self._critic = critic
        self._original_prompt = original_prompt

    def hook_point(self) -> HookPoint:
        return HookPoint.BEFORE_SCRIPT_OUTPUT

    async def run(self, context: dict[str, Any]) -> dict[str, Any] | None:
        """Run the critic before a script is actually saved to the workspace."""
        script_content = context.get("script_content", "")
        if not script_content:
            return None  # Nothing to review

        result = await self._critic.review_script(script_content, self._original_prompt)

        if not result.approved:
            # Overwrite context to reject the script save
            context["reject"] = True
            context["reject_reason"] = f"CRITIC AGENT REJECTED: {result.feedback}"
            return context

        # Approved
        return None
